# Generated by Django 5.0.4 on 2024-11-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('values', models.JSONField(default=list)),
                ('preferences', models.JSONField(default=list)),
                ('working_habits', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('race', models.CharField(max_length=50)),
                ('values', models.JSONField(default=list)),
                ('working_style', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
