# Generated by Django 5.0.4 on 2024-11-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_joblisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='flexibility',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='user',
            name='mental_health',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='user',
            name='work_life_balance',
            field=models.IntegerField(default=5),
        ),
    ]
