# Generated by Django 5.0.4 on 2024-11-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_user_flexibility_user_mental_health_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='flexibility',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='company',
            name='mental_health',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='company',
            name='work_life_balance',
            field=models.IntegerField(default=5),
        ),
    ]
