# Generated by Django 5.0.4 on 2024-11-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_company_flexibility_company_mental_health_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='preferences',
        ),
        migrations.RemoveField(
            model_name='company',
            name='working_habits',
        ),
    ]
