# Generated by Django 5.0.4 on 2024-11-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_company_preferences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='working_style',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
