# Generated by Django 5.0.4 on 2024-11-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_joblisting_working_style"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joblisting",
            name="salary",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
