# Generated by Django 5.0.4 on 2024-11-09 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0007_alter_joblisting_salary"),
        ("backend", "0007_user_skills"),
    ]

    operations = []
