# Generated by Django 5.0.4 on 2024-11-09 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_merge_0007_alter_joblisting_salary_0007_user_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('stars', models.IntegerField(default=3)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_reviews', to='backend.company')),
            ],
        ),
    ]
