# Generated by Django 5.0.4 on 2024-11-09 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_companyreview'),
        ('backend', '0009_request'),
    ]

    operations = [
    ]
