export const CORE_VALUES = [
  'Honesty',
  'Integrity',
  'Teamwork',
  'Innovation',
  'Excellence',
  'Respect',
  'Accountability',
  'Passion',
  'Courage',
  'Empathy',
];

export const RACES = [
  'Asian', 
  'Black or African American', 
  'Hispanic or Latino', 
  'White', 
  'Native American'
]

export const SKILLS = [
  "Agile Methodology",
  "Adaptability",
  "AutoCAD",
  "AWS (Amazon Web Services)",
  "Blockchain Technology",
  "Business Intelligence (BI)",
  "C++",
  "Cloud Computing",
  "Communication Skills",
  "Conflicts Resolution",
  "Creativity",
  "Critical Thinking",
  "Customer Service",
  "Data Analysis",
  "Data Visualization",
  "Decision Making",
  "Docker",
  "Digital Marketing",
  "Excel (Advanced)",
  "Emotional Intelligence",
  "Git/GitHub",
  "Google Cloud Platform (GCP)",
  "HTML/CSS",
  "Illustrator",
  "Java",
  "JavaScript",
  "Jira",
  "Leadership",
  "Machine Learning",
  "Mobile App Development (React Native, iOS, Android)",
  "Negotiation Skills",
  "Node.js",
  "Photoshop",
  "Power BI",
  "Problem-Solving",
  "Project Management Tools (Jira, Trello)",
  "Python",
  "React.js",
  "Ruby on Rails",
  "SQL",
  "SEO (Search Engine Optimization)",
  "Tableau",
  "Teamwork",
  "Time Management",
  "UI/UX Design",
  "Web Development",
  "WordPress"
];